### ISSUE TITLE
hi bro, I'm using your Valorant-YOLOv5-Aimbot, and my mouse is Logitech G304, but when I press F or H, it doesn't move to the character. Still stuck. Do you know what's going on. Thanks. Looking forward to your answer.

### ISSUE THREAD

**Issue by xiazaipw** [Leaf48/YOLOv5-7-Models-For-Valorant#11]
hi bro, I'm using your Valorant-YOLOv5-Aimbot, and my mouse is Logitech G304, but when I press F or H, it doesn't move to the character. Still stuck. Do you know what's going on. Thanks. Looking forward to your answer.

**Comment by xiazaipw** [comment]
> Hi. My repository has been already deleted. And you seemed to have got the repository from another person, not me. I only support public repository. So I ask that you contact that person, if you cannot solve the problem.
> 
> Thanks

Thank you. brother. Thanks for sharing,

**Comment by xiazaipw** [comment]
hi bro can you tell me what mouse are you using?

**Comment by Leaf48** [comment]
I've already checked working with Finalmouse / Gpro / Razer Viper v2(Wireless is unstable).
Note: It might be due to arduino program.

**Comment by xiazaipw** [comment]
Ok, then I'll change the mouse.

**Comment by Leaf48** [comment]
Good luck :)

**Comment by xiazaipw** [comment]
Thanks
